### ISSUE TITLE
Need to bump driver version in `shard.yml`

### ISSUE THREAD

**Issue by lachlan** [wonderix/crystal-tds#18]
@wonderix thank you for the latest `0.3.0` release of the `crystal-tds` driver! However I just noticed the version of `crystal-tds` is still `0.2.0` in `shard.yml` but should've been bumped to `0.3.0` to match the tag. Can you bump the version of the driver in `shard.yml` too please?

**Comment by wonderix** [comment]
I fixed this with c348e31efae0b02c0e4cc1b43bf1516460ac61a4
